#  https://github.com/marketplace?type=actions&query=checkout+
# Here we can find all the actions we want perform over the jobs.
name: Build & Deploy Spring app

#It will trigger the actions.
on:
  push: # when this pipeline will trigger.
    branches: # which branch to trigger.
      - main

# this jobs are we want to once the pipeline is up.
jobs:
  build-deploy:
    name: Build and Deploy Spring Boot
    # Machine which want to run.
    runs-on: ubuntu-latest # This is from GitHub actions.
#    Each jobs have different action.
#    First one is Check-out Code [copy the code and running into the runner above].
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 #This is GitHub Actions.

#        We need to setup jdk to run up the java applications
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
#      Testing the application
      - name: Unit Tests
        run : mvn -B test --file pom.xml
#        Create the package inside the runner
      - name: Build the Application
        run: |
          mvn clean
          mvn -B package --file pom.xml
        
        
